# external
require 'addressable/uri'
require 'json'
require 'net/http'
require 'ostruct'

# base/mixin/override
require 'verso/base'
require 'verso/hash'
require 'verso/http_get'

# resources and children
require 'verso/cluster'
require 'verso/cluster_list'
require 'verso/correlation_list'
require 'verso/course'
require 'verso/course_list'
require 'verso/credential'
require 'verso/credential_list'
require 'verso/duty_area'
require 'verso/edition_list'
require 'verso/emphasis'
require 'verso/emphasis_list'
require 'verso/examination_list'
require 'verso/extra'
require 'verso/extras_list'
require 'verso/frontmatter'
require 'verso/occupation'
require 'verso/occupation_data'
require 'verso/occupation_list'
require 'verso/pathway'
require 'verso/program_area_list'
require 'verso/program_area'
require 'verso/sol_correlation_list'
require 'verso/standard'
require 'verso/standards_list'
require 'verso/task'
require 'verso/task_list'

# gem version
require 'verso/version'
